name: Github Actions

# on: [push, pull_request]
on:
  push:
    branches: [  Release-Store  ]
    tags:
      - 'Store*'
  pull_request:
    branches: [  Release-Store  ]
jobs:
  build:
    runs-on: macOS-latest
#    container: reactnativecommunity/react-native-android
    steps:
        
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
   
    - name: Run a signing Certificate p12 script
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: dev.dayuan.rn3d
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: 'Another example step'
      run: echo ${{ steps.provisioning.outputs.profiles }}
   
    - name: "#️⃣ Generate Build Number"
      id: IOSbuild
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.ACTION_TEST }}
        prefix: IOSbuild

    - name: "#️⃣ Generate Build Number store"
      id: IOSVERSION
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.ACTION_TEST }}
        prefix: IOSVERSION
    - name: Print new build number
      run: |
        echo "Build number is $BUILD_NUMBER"
        echo "Build number is $buildnumber" ${{ steps.buildnumber.outputs.build_number }}
        echo "IOSVERSION is $buildnumber_store" ${{ steps.IOSVERSION.outputs.build_number }}
        echo "IOSbuild is $buildnumber" ${{ steps.IOSbuild.outputs.build_number }}
        echo "IOSVERSION is $buildnumber_store" ${{ steps.IOSVERSION.outputs }}
        echo "IOSbuild is $buildnumber" ${{ steps.IOSbuild.outputs }}

    - name: Install dependencies
      run: |    
        npm install -g react-native-cli
        yarn

    - name: Install IOS dependencies
      run: |    
        cd ios
        pod install
   
    - name: Build app (fix)
      run: |
        xcodebuild clean archive -workspace  ./ios/rn3d.xcworkspace -scheme rn3d  -archivePath ./ios/build/export.xcarchive  -showBuildTimingSummary MARKETING_VERSION=0.0.2  CURRENT_PROJECT_VERSION=6   archive
#        xcodebuild clean archive -workspace  ./ios/rn3d.xcworkspace -scheme rn3d  -archivePath ./ios/build/export.xcarchive  -showBuildTimingSummary CURRENT_PROJECT_VERSION="1"   archive
#            xcodebuild archive  -scheme rn3d  -sdk iphoneos -configuration Release -archivePath ../build/export     -showBuildTimingSummary     CURRENT_PROJECT_VERSION="41"   archive
 #     xcodebuild archive -scheme exp001  -sdk iphoneos  -configuration Release -archivePath /Users/sddivid/Documents/key/ios/9:3xcode/export    -showBuildTimingSummary CURRENT_PROJECT_VERSION="41"   archive 

    - name: Build IPA (APPLE)
      run: |
        xcodebuild -exportArchive -archivePath ./ios/build/export.xcarchive -exportPath ./build -exportOptionsPlist ./ios/ExportOptions.plist -allowProvisioningUpdates


    #Uploads
    - name: Upload archive
      if: steps.prepare_release.outputs.apk_path
      uses: actions/upload-artifact@v1
      with:
        name: xcarchive
        path: ./ios/build/export.xcarchive
    #Uploads
    - name: Upload ipa
      if: steps.prepare_release.outputs.bundle_path
      uses: actions/upload-artifact@v1
      with:
        name: ipa
        path: ./build/rn3d.ipa


    - uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: ./build/rn3d.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: show job status 3 
      if: always()
      id: job_status
      run: echo $status
      env:
         status: ${{job.status}}

    - name: send telegram message
      uses: appleboy/telegram-action@master
      if: always()
      with:
        to: ${{ secrets.TELEGRAM_TO_MESSAGEID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Below is the IOS for release job status: $status
      env:
         status: ${{job.status}}
#         document: ${{ github.workspace }}/${{steps.prepare_release.outputs.apk_path}}
