name: Github Actions

# on: [push, pull_request]
on:
  push:
    branches: [  master  ]
    tags:
      - 'v*'
  pull_request:
    branches: [  master  ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - name: "#️⃣ Generate Build Number"
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.ACTION_TEST }}
    - name: Print new build number
      run: |
        echo "Build number is $BUILD_NUMBER"
        echo "Build number is $buildnumber" ${{ steps.buildnumber.outputs.build_number }}
        echo  $BUILD_NUMBER
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      run: yarn install && cd android && chmod +x gradlew && ./gradlew assembleRelease
    #new

#     - name: Create release and upload apk
#       uses: underwindfall/create-release-with-debugapk@v2.0.0
#       env:
#           GITHUB_TOKEN: ${{ secrets.ACTION_TEST  }}
#       with:
#         tag_name: v1.0.2
#         asset_path: app/build/outputs/apk/debug/app-debug.apk
#         asset_name: Example.apk
#         asset_content_type: application/apk
    - name: Create GitHub release
      id: create_release
#       if: steps.version_check.outputs.changed == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TEST }}
      with:
        tag_name: V-${{ steps.buildnumber.outputs.build_number }}
        release_name: V-${{ steps.buildnumber.outputs.build_number }}
        body: |
          ![release!](https://i.giphy.com/media/lPulaaB9lDMnGZiivs/source.gif)
          # Changelog
          Release type: ${{ steps.buildnumber.outputs.build_number }}
        prerelease: true

    - name: Upload app binaries to releaseHub
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.ACTION_TEST  }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
#     - name: Upload binaries to release
#       uses: svenstaro/upload-release-action@v2
#       with:
#         repo_token: ${{ secrets.ACTION_TEST }}
#         file: ./app/build/outputs/apk/debug/app-debug.apk
#         asset_name: app-debug.apk
#         tag: V-${{ steps.buildnumber.outputs.build_number }}

#       if: steps.version_check.outputs.changed == 'true'
#     - name: Upload APKs to release assets
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:  
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./app/build/outputs/apk/debug/app-debug.apk
#         asset_name: app-debug.apk
#         asset_content_type: application/apk

        
        
        
       
