name: Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      run: yarn install && cd android && chmod +x gradlew && ./gradlew assembleRelease
    #new
    - name: "#️⃣ Generate Build Number"
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.ACTION_TEST }}
    - name: Print new build number
      run: |
        echo "Build number is $BUILD_NUMBER"
        echo "Build number is $buildnumber" ${{ steps.buildnumber.outputs }}
    - name: Create release and upload apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TEST  }}
      with:
        tag_name: v1.0.1
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: Example.apk
        asset_content_type: application/apk

